### ISSUE TITLE
Adding the function to play multiplayer with socket in your game

### ISSUE THREAD

**Issue by Adam-APT** [cuikho210/snake-game#1]
Your source code and your effort is really awesome. So please add the function to play multiple players with socket in your source code.
I want to learn from the complete source code.
P/s: How to detect the case of one snake collision with other snake?
Thank you!

**Comment by cuikho210** [comment]
Chào bạn!
Bạn có thể nói tiếng Việt được không ^^

Về việc phát triển thêm tính năng nhiều người chơi thì hoàn toàn có thể làm được, nhưng phải thay đổi ngôn ngữ backend từ PHP sang Nodejs. Mình nghĩ là cũng nhanh thôi vì backend của mình rất đơn giản, chủ yếu là sử dụng thêm socket, phát triển thêm chức năng nhiều người chơi sẽ tốn thêm thời gian.

Về việc phát hiện va chạm mình cũng từng nghiên cứu qua, nhưng không phải trong mã nguồn này. Trong project này mình sử dụng framework phaserjs, việc tính toán phát hiện va chạm đã được thư viện vật lý của framework làm cho rồi, mình chỉ cần xử lý khi có sự kiện va chạm xảy ra thôi. Đoạn mã xử lý ở [đây](https://github.com/cuikho210/snake-game/blob/14f6fce04f3bb94367a8a5a3846aca8eabcabace/game/game.js#L493), cũng chỉ có vài dòng thôi á ^^

**Comment by Adam-APT** [comment]
Cảm ơn bạn. Sorry, mình đang nghĩ là comment trên Github nên mình viết bằng tiếng anh.
1. Về phần va chạm, qua đoạn xử lý va chạm của bạn mình đã hiểu hơn về thư viện vật lý của phaser 3 rùi.
2. Giờ mình đang định hướng viết thêm function nhiều người chơi (kiểu kiểu giống slither.io) cho thành 1 source hoàn chỉnh để hoàn thành 1 series học Phaser. Vậy, phần properties của con rắn mình có thể gửi nhận qua socket để hiển thị được ở trên các người chơi khác nữa nhỉ?

**Comment by cuikho210** [comment]
Về vấn đề phát triển tính năng nhiều người chơi với socket thì bạn có thể tham khảo [bài viết này](https://phasertutorials.com/how-to-create-a-phaser-3-mmorpg-part-1/) nha. Bài viết gồm 3 phần rất chi tiết về cách phát triển 1 game MMORPG đơn giản bằng Phaserjs và Socket.io

**Comment by Adam-APT** [comment]
Cảm ơn bạn, để mình đọc thử bài này và làm thử. Nếu bạn rảnh thì bạn viết giúp mình học hỏi thêm với nha.
